name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install UV
        shell: pwsh
        run: |
          iwr https://astral.sh/uv/install.ps1 -UseBasicParsing | iex
          echo "$HOME\.local\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create venv and install deps
        shell: pwsh
        run: |
          uv venv
          uv sync -e test

      - name: Run tests
        shell: pwsh
        run: |
          uv run -m pytest --maxfail=1 --disable-warnings -q

